### ISSUE TITLE
Possible breaking change in wit api?

### ISSUE THREAD

**Issue by AlexGustafsson** [botpress/botpress-wit#1]
The example shows the following usage:

```javascript
bp.hear({'wit.entities.intent[0].value': 'weather'}, (event, next) => {
  console.log('>> Weather')
  bp.messenger.sendText(event.user.id, 'Weather intent')
})
```

This led me to believe that the wit object looks something like this:
```javascript
wit : {
  entities: {
    intent: [
      {value: "weather"}
    ]
  }
}
```

When in reality it looks more like this:
```javascript
wit: {
  entities:
  {
    "weather":[
      {"confidence":0.9,"type":"value","value":"weather"}
    ]
  }
}
```

This makes it so that the `condition` passed to `hear` used to retrieve the event value results in an invalid path. By using the example, `var eventValue = _lodash2.default.get(event, key, null);` (_lib/listeners.js line 24_) always results in `null`.

From what I can see, the `entities` object of `wit` is set directly from the wit npm module. Therefore it seems like `wit` may have changed their API. Perhaps botpress-wit should rewrite the object before continuing to use it?

Is there any quick fix for this?

**Comment by slvnperron** [comment]
@AlexGustafsson hey, so there seems to be no problem, just a small misunderstanding. In our examples, we have an entity called `intent` on our side:

![image](https://cloud.githubusercontent.com/assets/1315508/21932238/90d7c840-d96d-11e6-8b42-3027709d45d7.png)

In your case, you might want a condition more like:

```js
bp.hear({'wit.entities.weather': captures => {
    // check if we captured any weather entity at 90+% certainty
    return _.some(captures, c => c.confidence > 0.9)
}}, (event, next) => {
  bp.messenger.sendText(event.user.id, 'Weather intent')
})
```

That being said the documentation might be misleading. What do you suggest?

Thanks

**Comment by AlexGustafsson** [comment]
That makes sense. Thank you for providing the example. Perhaps you could export an example wit app and add it under a examples folder or something like that? That way one can explore the connection between the intents created in wit and the example code provided by botpress-wit. That or just clarify the wit setup - that "intent" is an intent setup in wit with one or more values, i.e. weather.

**Comment by slvnperron** [comment]
@AlexGustafsson makes sense, we'll definitely update both the doc and provide an example. Thanks!
