### ISSUE TITLE
Understanding feature broken

### ISSUE THREAD

**Issue by tguidon** [botpress/botpress-wit#4]
I'm pretty familiar with Wit and have trouble getting this working via the documentation. In the docs it's stated this will work for understanding intents:

```
bp.hear({'wit.entities.intent[0].value': 'weather'}, (event, next) => {
  console.log('>> Weather')
  bp.messenger.sendText(event.user.id, 'Weather intent')
})
```

I made a custom entity in wit just as you did named "intent" and it has the value "joke". I then tried this code in my index file:

```
  bp.hear({'wit.entities.intent[0].value': 'joke'}, (event, next) => {
    event.reply('Joke intent')
  })
```

to which I receive the error:

`_fulfillmentHandler0: [TypeError: expecting an array or an iterable object but got [object Null]],`

I'm not sure why this would be happening given my set up looks identical to yours. The message being logged before the error states that Wit is working properly.

`[message] Response: {"msg_id":"0Bh1joSlFBJVTGd5Y","_text":"joke?","entities":{"intent":[{"confidence":0.98142144476107,"value":"joke"}]}}`

Any ideas whats going on? Thanks!

**Comment by slvnperron** [comment]
Can you print the value of wit using the following code:

```js
bp.hear({ 'wit': () => true }, (event) => {
  console.log(event.wit)
})
```

So we have a better idea of what's going on. Thanks!

**Comment by tguidon** [comment]
```
09:02:55 - debug: [message] Response: {"msg_id":"0Mwy6ptagDgeAwPkW","_text":"joke?","entities":{"intent":[{"confidence":0.98142144476107,"value":"joke"}]}}
{ entities: { intent: [ [Object] ] },
  context:
   { begin: moment("2017-07-18T09:02:38.276"),
     sessionId: '/admin#gM9TwMhDKE0UlDmzAAAA+87602-82938',
     context: { botpress_platform: 'web', botpress_type: 'message' } } }
```

**Comment by slvnperron** [comment]
> Update for the community

It turns out that the error was in the reply:

```js
 event.reply('Joke intent') // invalid UMM block
```

We'll add extra verification and throw better error when UMM fails
